blog/urls.py
from django.urls import path
from blog import views

app_name = 'blog'

urlpatterns = [
    path('', views.BlogListView.as_view(), name='blog-list'),
    path('article/<int:pk>/<str:slug>/', views.BlogDetailView.as_view(), name='blog-detail'),
    path('tag/<int:pk>/<str:slug>/', views.BlogListView.as_view(), kwargs={'filter_type': 'tag'}, name='blog-tag'),
    path('category/<int:pk>/<str:slug>/', views.BlogListView.as_view(), kwargs={'filter_type': 'category'}, name='blog-category'),
    path('search/', views.BlogListView.as_view(), name='blog-search'),
]

compar_new/urls.py
from django.contrib import admin
from django.urls import include, path
from os import getenv
from django.conf.urls.static import static
from django.conf import settings
from django.views.generic import TemplateView
from django.contrib.sitemaps.views import sitemap
from compar_new.sitemaps import ArticleSitemap, CategorySitemap, StaticViewSitemap, TagSitemap
from django.conf.urls.i18n import i18n_patterns
from . import views

sitemaps = {
    'static': StaticViewSitemap,
    'article': ArticleSitemap,
    'tag': TagSitemap,
    'category': CategorySitemap
}

urlpatterns = [
    # path('robots.txt', TemplateView.as_view('')),
    path(getenv('ADMIN_URL'), admin.site.urls),
    path('i18n/', include('django.conf.urls.i18n')),
    path('sitemap.xml', sitemap, {'sitemaps': sitemaps}, name='django.contrib.sitemaps.views.sitemap'),
    path('robots.txt', TemplateView.as_view(template_name='robots.txt', content_type='text/plain'), name='robots'),
    path('ckeditor/', include('ckeditor_uploader.urls')),
    
] + static(settings.MEDIA_URL)




handler404 = 'compar_new.views.handler_error_view'
handler500  = 'compar_new.views.handler_error_view'


urlpatterns += i18n_patterns(
    path('blog/', include('blog.urls')),
    path('events/', include('event.urls')),
    path('', include('promotion.urls')),
    path('courses/', include('course.urls')),
)

course/urls.py
from django.urls import path
from . import views

app_name = 'course'

urlpatterns = [
    path('', views.courses, name='courses'),
    path('<int:pk>/<str:slug>/', views.course_detail, name='course-detail'),
]

promotion/urls.py
from django.urls import path
from promotion import views

app_name = 'promotion'
urlpatterns = [
    path('', views.home, name='home'),
    path('contact/', views.contact, name='contact'),
    path('about/', views.about, name='about'),
    path('faq/', views.faq, name='faq'),
    path('graduates/', views.graduates, name='graduates'),
    path('method/', views.method, name='method'),
    path('packages/', views.packages, name='packages'),
    path('corporative/', views.corporative, name='corporative'),
    path('appointment/', views.appointment, name='appointment'),
    path('privacy/', views.privacy, name='privacy'),
]

promotion/models.py
from tabnanny import verbose
from django.db import models

# Create your models here.
class Appointment(models.Model):
    name = models.CharField(max_length=100, null=False, blank=False, verbose_name='Ad, Soyad')
    contact = models.CharField(max_length=100, null=False, blank=False, verbose_name='Email və ya Telefon')
    subject = models.CharField(max_length=100, null=False, blank=False, verbose_name='Mövzu')
    message = models.TextField(null=False, blank=False, verbose_name='Mesaj')
    viewed = models.BooleanField(default=False, verbose_name='Baxdım')
    created = models.DateField(auto_now_add=True, verbose_name='Göndərilmə Tarixi')

    class Meta:
        ordering = ['-created']
        verbose_name = 'Müraciət'
        verbose_name_plural = 'Müraciətlər'

    def __str__(self):
        return self.name + ' müraciət'
    
    
class Slider(models.Model):
    headline = models.CharField(max_length=100, null=False, blank=False, verbose_name='Başlıq')
    title = models.CharField(max_length=100, null=False, blank=False, verbose_name='Başlıq')
    description = models.TextField(null=False, blank=False, verbose_name='Mətn')
    image = models.ImageField(upload_to='slider/', null=False, blank=False, verbose_name='Şəkil')
    updated = models.DateField(auto_now=True, verbose_name='Yenilənmə Tarixi')
    created = models.DateField(auto_now_add=True, verbose_name='Yaradılma Tarixi')

    class Meta:
        ordering = ['-created']
        verbose_name = 'Slider'
        verbose_name_plural = 'Sliderlər'

    def __str__(self):
        return self.title + ' slider'


class StudentReview(models.Model):
    profile_picture = models.ImageField(upload_to='student/', null=False, blank=False, verbose_name='Profil Şəkli')
    full_name = models.CharField(max_length=100, null=False, blank=False, verbose_name='Ad, Soyad')
    job_title = models.CharField(max_length=100, null=False, blank=False, verbose_name='Vəzifə')
    comment = models.TextField(null=False, blank=False, verbose_name='Rəy')
    updated = models.DateField(auto_now=True, verbose_name='Yenilənmə Tarixi')
    created = models.DateField(auto_now_add=True, verbose_name='Yaradılma Tarixi')
    
    class Meta:
        ordering = ['-created']
        verbose_name = 'Tələbə Rəyi'
        verbose_name_plural = 'Tələbə Rəyləri'
        
    def __str__(self):
        return self.full_name + ' rəyi'


class Alumni(models.Model):
    profile_picture = models.ImageField(upload_to='alumni/', null=False, blank=False, verbose_name='Profil Şəkli')
    full_name = models.CharField(max_length=100, null=False, blank=False, verbose_name='Ad, Soyad')
    job_title = models.CharField(max_length=100, null=False, blank=False, verbose_name='Vəzifə')
    linkedin_url = models.URLField(max_length=200, null=False, blank=False, verbose_name='Linkedin URL')
    updated = models.DateField(auto_now=True, verbose_name='Yenilənmə Tarixi')
    created = models.DateField(auto_now_add=True, verbose_name='Yaradılma Tarixi')
    
    class Meta:
        ordering = ['-created']
        verbose_name = 'Alumni'
        verbose_name_plural = 'Alumni'
        
    def __str__(self):
        return self.full_name + ' Alumni'
    
    
class Faq(models.Model):
    question = models.TextField(null=False, blank=False, verbose_name='Sual')
    answer = models.TextField(null=False, blank=False, verbose_name='Cavab')
    updated = models.DateField(auto_now=True, verbose_name='Yenilənmə Tarixi')
    created = models.DateField(auto_now_add=True, verbose_name='Yaradılma Tarixi')
    
    class Meta:
        ordering = ['-created']
        verbose_name = 'FAQ'
        verbose_name_plural = 'FAQ'
        
    def __str__(self):
        return self.question + ' sualı'
    
    
class AboutStatictic(models.Model):
    title = models.CharField(max_length=100, null=False, blank=False, verbose_name='Başlıq')
    count = models.IntegerField(default=0, verbose_name='Say')
    description = models.TextField()
    updated = models.DateField(auto_now=True, verbose_name='Yenilənmə Tarixi')
    created = models.DateField(auto_now_add=True, verbose_name='Yaradılma Tarixi')
    
    class Meta:
        ordering = ['-created']
        verbose_name = 'Haqqımızda Statistika'
        verbose_name_plural = 'Haqqımızda Statistikalar'
        
    def __str__(self):
        return self.title + ' statistikası'
    
class StudentProjectTag(models.Model):
    title = models.CharField(max_length=100, null=False, blank=False, verbose_name='Başlıq')
    updated = models.DateField(auto_now=True, verbose_name='Yenilənmə Tarixi')
    created = models.DateField(auto_now_add=True, verbose_name='Yaradılma Tarixi')
    
    class Meta:
        ordering = ['-created']
        verbose_name = 'Tələbə Layihəsi Teq'
        verbose_name_plural = 'Tələbə Layihəsi Teqləri'
        
    def __str__(self):
        return self.title + ' tag'
        
        
class StudentProject(models.Model):
    title = models.CharField(max_length=100, null=False, blank=False, verbose_name='Başlıq')
    description = models.TextField(null=False, blank=False, verbose_name='Mətn')
    image = models.ImageField(upload_to='student/project/', null=False, blank=False, verbose_name='Şəkil')
    project_url = models.URLField(max_length=200, null=False, blank=False, verbose_name='Layihə URL')
    tags = models.ManyToManyField(StudentProjectTag, verbose_name='Teqlər')
    updated = models.DateField(auto_now=True, verbose_name='Yenilənmə Tarixi')
    created = models.DateField(auto_now_add=True, verbose_name='Yaradılma Tarixi')
    
    class Meta:
        ordering = ['-created']
        verbose_name = 'Tələbə Layihəsi'
        verbose_name_plural = 'Tələbə Layihələri'
        
    def __str__(self):
        return self.title + ' layihəsi'
    

promotion/forms.py
from django.forms import ModelForm
from promotion.models import Appointment

class AppointmentForm(ModelForm):
    class Meta:
        model = Appointment
        fields = ('name', 'contact', 'subject', 'message')

promotion/views.py
from django.shortcuts import redirect, render
from django.urls import reverse
from promotion.forms import AppointmentForm
from blog.models import Article
from promotion.models import Slider, StudentReview, Alumni, StudentProject, StudentProjectTag, AboutStatictic, Faq
from os import getenv
import requests
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger

# Create your views here.


def home(request):
    packages = Article.objects.filter(
        category__title='Tədris Paketləri').order_by('created')
    articles = Article.objects.exclude(category__title='Tədris Paketləri')[:5]
    sliders = Slider.objects.all()
    student_reviews = StudentReview.objects.all()
    student_projects = StudentProject.objects.all()
    student_projects_tags = StudentProjectTag.objects.all()
    alumnies = Alumni.objects.all()
    return render(request, 'home.html', context={
        'packages': packages, 'articles': articles, 'sliders': sliders, 'student_reviews': student_reviews,
        'alumnies': alumnies, 'student_projects': student_projects, 'student_projects_tags': student_projects_tags,
    })


def contact(request, appointment=None):
    return render(request, 'contact.html', context={'appointment': appointment})


def about(request):
    about_statistics = AboutStatictic.objects.all()
    return render(request, 'about.html', context={
        'about_statistics': about_statistics
    })


def faq(request):
    faqs = Faq.objects.all()
    return render(request, 'faq.html', {'faqs': faqs})


def graduates(request):
    alumnies = Alumni.objects.all()
    student_projects = StudentProject.objects.all()
    student_projects_tags = StudentProjectTag.objects.all()
    paginator = Paginator(student_projects, 8)  
    page_number = request.GET.get('page')  

    try:
        student_projects = paginator.page(page_number)
    except PageNotAnInteger:
        student_projects = paginator.page(1)
    except EmptyPage:
        student_projects = paginator.page(paginator.num_pages)

    return render(request, 'graduates.html', context={
        'alumnies': alumnies,
        'student_projects_tags': student_projects_tags,
        'student_projects': student_projects,
        'is_paginated': True, 
        'page_obj': student_projects,  
        'paginator': paginator, 
    })


def method(request):
    return render(request, 'method.html')


def packages(request):
    articles = Article.objects.filter(
        category__title='Tədris Paketləri').order_by('created')
    return render(request, 'customs/promotion/packages.html', context={'articles': articles})


def corporative(request):
    return render(request, 'customs/promotion/corporative.html')


def appointment(request):
    if request.method == 'POST':
        recaptcha_response = request.POST.get('g-recaptcha-response')
        secret_key = getenv('RECAPTCHA_SECRET_KEY')
        response = requests.post('https://www.google.com/recaptcha/api/siteverify', data={
            'secret': secret_key,
            'response': recaptcha_response
        }).json()
        form = AppointmentForm(request.POST)
        if form.is_valid() and 'score' in response and response.get('score') > 0.7:
            appointment_instance = form.save()
            appointment_instance.save()
            return redirect(reverse('promotion:contact') + '?success=true')
        else:
            return redirect(reverse('promotion:contact') + '?success=false')
    else:
        return redirect('promotion:contact')
    


def privacy(request):
    return render(request, 'customs/promotion/privacy.html')

promotion/templates/faq.html
{% extends 'layout.html' %}
{% block title %}
  <title>FAQ - Compar Academy İxtisaslaşmış Tədris Mərkəzi</title>
{% endblock title %}
{% load static %} 
{% block meta_tags %}
  <meta name="description" content="Sualınız var? Tez-tez verilən suallar bölməsi sizə yardımçı ola bilər.">
  <meta property="og:title" content="FAQ - Compar Academy İxtisaslaşmış Tədris Mərkəziniz" />
  <meta property="og:description" content="Sualınız var? Tez-tez verilən suallar bölməsi sizə yardımçı ola bilər." />
  <meta property="og:type" content="article" />
  <meta property="og:url" content="{{request.build_absolute_uri}}" />
  <meta property="og:image" content="{% static "assets/compar-logo-header.png" %}" />
{% endblock meta_tags %} 
{% block main %}
<section id="faq-first">
  <div class="faq-first-main-box">
    <img class="img-fluid" src="{% static "assets/faq-first.png" %}" alt="" />
    <div class="img-overlay"></div>
    <div class="faq-first-title">
      <h1>Ən çox verilən<br />suallar</h1>
    </div>
  </div>
</section>
<section id="questions">
  <div class="container-fluid">
    <div class="row row-gap-5">
      {% for faq in faqs %}
      <div class="col-12 col-lg-6">
        <div class="d-flex justify-content-center align-items-center faq-open">
          <h6>
            {{ faq.question }}
          </h6>
          <i class="fa-solid fa-chevron-down"></i>
        </div>
        <p>
          {{ faq.answer }}
        </p>
      </div>
      {% endfor %}
    </div>
  </div>
</section>
<section id="faq-form">
  <form id="contactForm" method="POST" action="{% url 'promotion:appointment' %}">
    {% csrf_token %}
    <input type="text" name="name" placeholder="Ad, Soyad" required />
    <input type="text" name="contact" placeholder="Email və ya Telefon" required />
    <input type="text" name="subject" placeholder="Mövzu" required />
    <textarea name="message" placeholder="Mesaj" cols="30" rows="10" required></textarea>
    <p style="color:green; font-size:20px; {% if request.GET.success == 'true' %}display:block;{% else %}display:none;{% endif %}">Form uğurla göndərildi</p>
    <p style="color:red; font-size:20px; {% if request.GET.success == 'false' %}display:block;{% else %}display:none;{% endif %}">Zəhmət olmasa formu düzgün daxil edin</p>
    <button class="btn compar-gradient-button g-recaptcha" data-sitekey="6Le34x0iAAAAABD4mQucCFf2lwhLKYL40j9eEqWx" data-callback='onSubmit' data-action='submit'>Submit</button>
  </form>
</section>

{% endblock main %}

{% block scripts %}
    <script src="{% static 'customs/contact/contact.min.js' %}"></script>
    <script src="https://www.google.com/recaptcha/api.js"></script>
    <script>
        function onSubmit(token) {
          document.getElementById("contactForm").submit();
        }
      </script>
{% endblock scripts %}

promotion/templates/home.html
{% extends 'layout.html' %}
{% block title %}
  <title>Ana Səhifə - Compar Academy İxtisaslaşmış Tədris Mərkəzi</title>
{% endblock title %}
{% load static %}
{% block meta_tags %}
<meta name="description" content="Məqsədimiz tədrisini etdiyimiz sahələrə marağı olan insanlara motivasiya vermək, düzgün istiqamətləndirmək və gələcəklərinə müsbət təsir göstərməkdir.">
<meta property="og:title" content="Ana Səhifə - Compar Academy İxtisaslaşmış Tədris Mərkəzi" />
<meta property="og:description" content="Məqsədimiz tədrisini etdiyimiz sahələrə marağı olan insanlara motivasiya vermək, düzgün istiqamətləndirmək və gələcəklərinə müsbət təsir göstərməkdir." />
<meta property="og:type" content="website" />
<meta property="og:url" content="{{request.build_absolute_uri}}" />
<meta property="og:image" content="{% static "assets/compar-logo-header.png" %}" />
{% endblock meta_tags %} 
{% block main %}
{% load article_tags %} {% get_articles as articles %}
{% load course_tags %} {% get_courses as courses %}
<section id="home-main-slider">
  <div class="slider">
    <div class="list">
      {% for slider in sliders %}
      <div class="item {% if forloop.first %}active{% endif %}">
        <img src="{{ slider.image.url }}" />
        <div class="content">
          <p>{{ slider.headline }}</p>
          <h2>{{ slider.title }}</h2>
          <p>{{ slider.description }}</p>
        </div>
      </div>
      {% endfor %}
    </div>
    <div class="arrows">
      <button id="prev"><</button>
      <button id="next">></button>
    </div>
    <div class="thumbnail">
      {% for slider in sliders %}
      <div class="item {% if forloop.first %}active{% endif %}">
        <img src="{{ slider.image.url }}" />
        <div class="content">{{ slider.title }}</div>
      </div>
      {% endfor %}
    </div>
  </div>
</section>
<section id="education">
  <div class="education-first-content">
    <h2>Tədris sahələrimiz</h2>
    <p>
      Lorem Ipsum is simply dummy text of the printing and<br />typesetting
      industry
    </p>
  </div>
  <div class="container-fluid">
    <div class="row row-gap-4">
      <div class="slider-container">
        <div class="swiper mySwiper2">
          <div class="swiper-wrapper">
            {% for course in courses %}
            <div class="swiper-slide">
              <div class="img-box">
                <img src="{{ course.image.url }}" alt="{{ course.title }}" />
                <div class="img-overlay"></div>
                <div class="img-button2">
                  <i class="fa-solid fa-arrow-right"></i>
                </div>
              </div>
              <div class="education-content">
                <a href="{% url 'course:course-detail' pk=course.pk slug=course.slug %}">{{ course.title }}</a>
                <p>{{ course.description|slice:":60"}}...</p>
                <div class="education-tags">
                  {% for tag in course.tags.all %}
                  <div class="colorful-tags java-tag">{{ tag.title }}</div>
                  {% endfor %}
                </div>
              </div>
            </div>
            {% endfor %}
          </div>
        </div>
        <div class="button-prev">
          <i class="fa-solid fa-arrow-left-long"></i>
        </div>
        <div class="button-next">
          <i class="fa-solid fa-arrow-right-long"></i>
        </div>
      </div>
    </div>
  </div>
</section>
<section id="why-us">
  <div class="container-fluid">
    <div class="row">
      <div class="col-12 col-md-12 col-lg-6 why-us-none">
        <div class="why-us-img-box">
          <img class="why-us-img1" src="{% static "assets/why-us-img1.png" %}" alt="" />
          <img class="why-us-img2" src="{% static "assets/why-us-img2.png" %}" alt="" />
          <img class="why-us-img3" src="{% static "assets/why-us-img3.png" %}" alt="" />
          <div class="appeal-button"><a href="{% url 'promotion:contact' %}">İndi müraciət et</a></div>
        </div>
      </div>
      <div class="col-12 col-md-12 col-lg-6 m-auto">
        <h2>Niyə BİZ?</h2>
        <p class="why-us-content-p">
          Compar Academy veb-proqramlaşdırma, qrafik dizayn, veb dizayn,
          Microsoft Office, interyer dizayn kimi yüksək kompüter ixtisasları
          üzrə peşəkarlaşmış tədris mərkəzidir.
        </p>
        <div class="container-fluid">
          <div class="row row-gap-5">
            <div class="col-12 col-md-6 col-lg-6">
              <div class="d-flex align-items-center">
                <img
                  style="width: 34px; height: 34px"
                  src="{% static "assets/why-us-icon1.png" %}"
                  alt="why-us-icon1"
                />
                <div class="why-us-icon-content">
                  <div class="why-us-icon-content-h">Təcrübə programı</div>
                  <div class="why-us-icon-content-p">
                    Lorem Ipsum is simply dummy text of the printing and
                    typesetting industry
                  </div>
                </div>
              </div>
            </div>
            <div class="col-12 col-md-6 col-lg-6">
              <div class="d-flex align-items-center">
                <img
                  style="width: 34px; height: 34px"
                  src="{% static "assets/why-us-icon2.png" %}"
                  alt="why-us-icon2"
                />
                <div class="why-us-icon-content">
                  <div class="why-us-icon-content-h">Xaricdə praktika</div>
                  <div class="why-us-icon-content-p">
                    Lorem Ipsum is simply dummy text of the printing and
                    typesetting industry
                  </div>
                </div>
              </div>
            </div>
            <div class="col-12 col-md-6 col-lg-6">
              <div class="d-flex align-items-center">
                <img
                  style="width: 34px; height: 34px"
                  src="{% static "assets/why-us-icon3.png" %}"
                  alt="why-us-icon3"
                />
                <div class="why-us-icon-content">
                  <div class="why-us-icon-content-h">Mentor sistemi</div>
                  <div class="why-us-icon-content-p">
                    Lorem Ipsum is simply dummy text of the printing and
                    typesetting industry
                  </div>
                </div>
              </div>
            </div>
            <div class="col-12 col-md-6 col-lg-6">
              <div class="d-flex align-items-center">
                <img
                  style="width: 34px; height: 34px"
                  src="{% static "assets/why-us-icon4.png" %}"
                  alt="why-us-icon4"
                />
                <div class="why-us-icon-content">
                  <div class="why-us-icon-content-h">Karyera dəstəyi</div>
                  <div class="why-us-icon-content-p">
                    Lorem Ipsum is simply dummy text of the printing and
                    typesetting industry
                  </div>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</section>
<section id="portfolio">
  <div class="portfolio-content">
    <div class="d-flex justify-content-between">
      <div class="portfolio-first-content">
        <h2>Tələbələrin işləri</h2>
        <p>
          Lorem Ipsum is simply dummy text of the printing and<br />typesetting
          industry
        </p>
      </div>
      <div class="portfolio-button">
        <a href="{% url 'promotion:graduates' %}">hamısı</a>
      </div>
    </div>
    <div class="portfolio-boxes">
      {% for project in student_projects|slice:"0:3" %}
        <div class="portfolio-box">
          <div class="portfolio-box-main">
            <img src="{{ project.image.url }}" alt="{{ project.title }}" />
            <div class="portfolio-colorful-tags d-flex">
                {% for tag in project.tags.all %}
                    <div class="asset-tag colorful-tags">{{ tag.title }}</div>
                {% endfor %}
            </div>
            <div class="portfolio-content">
                <h2>{{ project.title }}</h2>
                <p>{{ project.description }}</p>
            </div>
            <a href="{{ project.project_url }}">
                <div class="portfolio-btn d-flex align-items-center">
                    See the project
                    <i class="fa-solid fa-chevron-right"></i>
                </div>
            </a>
            </div>
          </div>
          {% endfor %}
    </div>
  </div>
  <div class="portfolio-slider">
    <div class="swiper mySwiper3">
      <div class="swiper-wrapper">
        {% for project in student_projects|slice:"0:3" %}
        <div class="swiper-slide">
          <div class="portfolio-slider-box">
            <div class="portfolio-box-main">
              <img src="{{ project.image.url }}" alt="{{ project.title }}" />
              <div class="portfolio-colorful-tags d-flex">
                {% for tag in project.tags.all %}
                <div class="asset-tag colorful-tags">{{ tag.title }}</div>
                {% endfor %}
              </div>
              <div class="portfolio-content">
                <h2>{{ project.title }}</h2>
                <p>{{ project.description }}</p>
              </div>
              <a href="{{ project.project_url }}">
                <div class="portfolio-btn d-flex align-items-center">
                    See the project
                    <i class="fa-solid fa-chevron-right"></i>
                </div>
            </a>
            </div>
          </div>
        </div>
        {% endfor %}
      </div>
      <div class="swiper-scrollbar"></div>
    </div>
  </div>
</section>
<section id="slider-student-review">
  <div class="student-review-title">Tələbələrimizin rəyləri</div>
  <div class="slider-container">
    <div class="swiper mySwiper1">
      <div class="swiper-wrapper">
        {% for review in student_reviews %}
        <div class="swiper-slide">
          <div class="slider-element">
            <div class="slider-content">
              "{{ review.comment }}"
            </div>
            <div class="d-flex">
              <div class="slider-student">
                <div class="d-flex align-items-center">
                  <img src="{{ review.profile_picture.url }}" alt="slider-student-image" />
                  <div class="slider-student-info">
                    <div class="slider-student-name">{{ review.full_name }}</div>
                    <div class="slider-student-job">{{ review.job_title }}</div>
                  </div>
                </div>
              </div>
              <div class="d-flex ms-auto">
                <div class="slider-first-icon">
                  <i class="quote fa-solid fa-quote-left"></i>
                </div>
                <div class="slider-second-icon">
                  <i class="quote fa-solid fa-quote-right"></i>
                </div>
              </div>
            </div>
          </div>
        </div>
        {% endfor %}
      </div>
      <div class="swiper-scrollbar"></div>
    </div>
    <div class="button-prev">
      <i class="fa-solid fa-arrow-left-long"></i>
    </div>
    <div class="button-next">
      <i class="fa-solid fa-arrow-right-long"></i>
    </div>
  </div>
</section>
<section id="blog">
  <div class="d-flex justify-content-between py-5">
    <div class="blog-first-content">
      <h2>Blog</h2>
      <p>
        Lorem Ipsum is simply dummy text of the printing and<br />typesetting
        industry
      </p>
    </div>
    <div class="blog-button">
      <a href="{% url 'blog:blog-list' %}">hamısı</a>
    </div>
  </div>
  <div class="container-fluid">
    <div class="row row-gap-4">
      {% for article in articles|slice:"0:2" %}
          <div class="col-12 col-md-6">
            <div class="blog-main">
              <img class="first-main-img" src="{{ article.main_image.url }}" alt="{{ article.title }}" />
              <div class="blog-name">{{ article.category }}</div>
              <div class="underside">
                <h3>{{ article.title }}</h3>
                <p>{{ article.description }}</p>
              </div>
              <div class="blog-button">
                <a href="{% url 'blog:blog-detail' pk=article.pk slug=article.slug %}">
                    <i class="fa-solid fa-angle-right"></i>
                </a>
            </div>
            </div>
          </div>
      {% endfor %}
    </div>
  </div>
</section>
<section id="graduates">
  <div class="d-flex justify-content-between">
    <div class="graduates-first-content">
      <h2>Məzunlarımız</h2>
      <p>
        Lorem Ipsum is simply dummy text of the printing and<br />typesetting
        industry
      </p>
    </div>
    <div class="graduates-button">
      <a href="{% url 'promotion:graduates' %}">hamısı</a>
    </div>
  </div>
  <div class="container-fluid">
    <div class="graduates-main">
      {% for alumni in alumnies|slice:"0:10" %}
      <div class="student">
        <img src="{{ alumni.profile_picture.url }}" alt="{{ alumni.full_name }}" />
        <div class="student-info">
          <div class="student-name">{{ alumni.full_name }}</div>
          <div class="student-job">{{ alumni.job_title }}</div>
          <a href="{{ alumni.linkedin_url}}">
            <i class="fa-brands fa-linkedin-in"></i>
          </a>
        </div>
      </div>
      {% endfor %}
    </div>
  </div>
</section>
{% endblock main %}