blog/urls.py
from django.urls import path
from blog import views

app_name = 'blog'

urlpatterns = [
    path('', views.BlogListView.as_view(), name='blog-list'),
    path('article/<int:pk>/<str:slug>/', views.BlogDetailView.as_view(), name='blog-detail'),
    path('tag/<int:pk>/<str:slug>/', views.BlogListView.as_view(), kwargs={'filter_type': 'tag'}, name='blog-tag'),
    path('category/<int:pk>/<str:slug>/', views.BlogListView.as_view(), kwargs={'filter_type': 'category'}, name='blog-category'),
    path('search/', views.BlogListView.as_view(), name='blog-search'),
]

compar_new/urls.py
from django.contrib import admin
from django.urls import include, path
from os import getenv
from django.conf.urls.static import static
from django.conf import settings
from django.views.generic import TemplateView
from django.contrib.sitemaps.views import sitemap
from compar_new.sitemaps import ArticleSitemap, CategorySitemap, StaticViewSitemap, TagSitemap
from django.conf.urls.i18n import i18n_patterns
from . import views

sitemaps = {
    'static': StaticViewSitemap,
    'article': ArticleSitemap,
    'tag': TagSitemap,
    'category': CategorySitemap
}

urlpatterns = [
    # path('robots.txt', TemplateView.as_view('')),
    path(getenv('ADMIN_URL'), admin.site.urls),
    path('i18n/', include('django.conf.urls.i18n')),
    path('sitemap.xml', sitemap, {'sitemaps': sitemaps}, name='django.contrib.sitemaps.views.sitemap'),
    path('robots.txt', TemplateView.as_view(template_name='robots.txt', content_type='text/plain'), name='robots'),
    path('ckeditor/', include('ckeditor_uploader.urls')),
    
] + static(settings.MEDIA_URL)




handler404 = 'compar_new.views.handler_error_view'
handler500  = 'compar_new.views.handler_error_view'


urlpatterns += i18n_patterns(
    path('blog/', include('blog.urls')),
    path('events/', include('event.urls')),
    path('', include('promotion.urls')),
    path('courses/', include('course.urls')),
)

blog/models.py
from django.db import models
from ckeditor.fields import RichTextField
from django.urls import reverse
from utils.model.field_utils import get_image_tag, get_slug, get_slug_link
from imagekit.models import ProcessedImageField
from django.utils import timezone
from minify_html import minify
from django.contrib.admin import display


# Create your models here.

class Tag(models.Model):
    title = models.CharField(max_length=50, verbose_name='Ad')
    updated = models.DateField(auto_now = True, verbose_name='Dəyişdirildi')
    created = models.DateField(auto_now_add=True, verbose_name='Yaradıldı')

    class Meta:
        ordering = ['-updated']
        verbose_name = 'Teq'
        verbose_name_plural = 'Teqlər'

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse("blog:blog-tag", kwargs={'pk': self.pk, 'slug': self.slug})

    @property
    def slug(self):
        return get_slug(self.title) if self.title and self.pk else None

    @display(description='Link')
    def slug_link(self):
        return get_slug_link(self.slug, self.get_absolute_url)

class Category(models.Model):
    title = models.CharField(max_length=50, verbose_name='Ad')
    updated = models.DateField(auto_now = True, verbose_name='Dəyişdirildi')
    created = models.DateField(auto_now_add=True, verbose_name='Yaradıldı')
    class Meta:
        ordering = ['-updated']
        verbose_name = 'Kateqoriya'
        verbose_name_plural = 'Kateqoriyalar'

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse("blog:blog-category", kwargs={'pk': self.pk, 'slug': self.slug})


    @property
    def slug(self):
        return get_slug(self.title) if self.title and self.pk else None

    @display(description='Link')
    def slug_link(self):
        return get_slug_link(self.slug, self.get_absolute_url)



class Article(models.Model):
    title = models.TextField(verbose_name='Başlıq')
    slug = models.SlugField(verbose_name='Slug', null=True, blank=True, max_length=100)
    description = models.TextField(verbose_name='Açıqlama')
    content = RichTextField(verbose_name='Kontent')
    main_image =ProcessedImageField(upload_to='blog/article/', options={'quality': 70}, verbose_name='Əsas Şəkil')
    vector_image = ProcessedImageField(upload_to='blog/article-vector/', options={'quality': 70}, verbose_name='Vektor Şəkli', null=True, blank=True, default=None)
    tags = models.ManyToManyField(Tag, verbose_name='Teqlər')
    viewed = models.IntegerField(default=0, verbose_name='İzlənilmə Sayı')
    show = models.BooleanField(default=True, verbose_name='Göstərilsin')
    category = models.ForeignKey(Category, on_delete=models.SET_NULL, null=True, blank=False)
    updated = models.DateField(default=None, null=True, blank=True, verbose_name='Dəyişdirildi')
    created = models.DateField(auto_now_add=True, verbose_name='Yaradıldı')

    class Meta:
        ordering = ['-updated']
        verbose_name = 'Məqalə'
        verbose_name_plural = 'Məqalələr'

    def __str__(self):
        return self.title

    def save(self, const_updated_date=False):
        if not const_updated_date:
            self.updated = timezone.localdate()
            self.content = minify(self.content)
            self.slug = get_slug(self.title) if self.title and self.pk else None
        return super().save()
    
    @display(description='Mövcud Əsas Şəkil')
    def main_image_tag(self):
        return get_image_tag(self.main_image.url)

    @display(description='Mövcud Vektor Şəkli')
    def vector_image_tag(self):
        return get_image_tag(self.vector_image.url)

    @display(description='Kateqoriya')
    def category_title(self):
        return self.category.title

    @display(description='Link')
    def slug_link(self):
        return get_slug_link(self.slug, self.get_absolute_url)
    
    def get_absolute_url(self):
        return reverse("blog:blog-detail", kwargs={"pk": self.pk, 'slug': self.slug})
    

    def related_articles(self, count=5):
        return Article.objects.filter(tags__in=self.tags.all()
        ).annotate(common_tags_count=models.Count('pk')).order_by('-common_tags_count'
        ).exclude(pk=self.pk)[:count]

    def get_image(self):
        if self.vector_image:
            return self.vector_image.url
        else:
            return self.main_image.url

    def get_seo_title(self):
        length = len(self.title)
        if length > 59:
            return self.title[:56] + '...'
        elif length < 9:
            return self.title + ' - Compar Academy İxtisaslaşmış Tədris Mərkəziniz'
        elif length < 19:
            return self.title + ' - Compar Academy İxtisaslaşmış Tədris'
        elif length < 29:
            return self.title + ' - Compar Academy Tədirs Mərkəzi'
        elif length < 39:
            return self.title + ' - Compar Academy'
        elif length < 49:
            return self.title + ' - Compar'
        else:
            return self.title


class ArticleImage(models.Model):
    image_file = ProcessedImageField(upload_to='blog/article-image/', options={'quality': 50})
    article = models.ForeignKey(Article, on_delete=models.CASCADE)
    updated = models.DateField(auto_now = True, verbose_name='Dəyişdirildi')
    created = models.DateField(auto_now_add=True, verbose_name='Yaradıldı')

    def image_file_tag(self):
        return get_image_tag(self.image_file.url)
    image_file_tag.short_description = 'Mövcud Əsas Şəkil'

    def __str__(self):
        return f'"{self.article.title}" məqalə şəkli'

blog/views.py
from django.shortcuts import render
from django.views.generic.list import ListView
from django.views.generic.detail import DetailView
from blog.models import Article, Tag, Category
from utils.model.view.pagination import get_page_list
from django.contrib.postgres.search import SearchVector, SearchQuery, SearchRank
from django.db.models import Count
from django.db.models import F

# Create your views here.
def blog_list(request):
    return render(request, 'blog.html')

def blog_detail(request):
    return render(request, 'blog-detail.html')


class BlogListView(ListView):
    paginate_by = 6
    template_name = 'blog.html'
    context_object_name = 'articles'
    queryset = Article.objects.all().filter(show=True).order_by('-created')

    def get_queryset(self):
        pk = self.kwargs.get('pk')
        keyword = self.request.GET.get('keyword')
        if pk and self.kwargs.get('filter_type') == 'tag':
            return super().get_queryset().filter(tags=pk)
        elif pk and self.kwargs.get('filter_type') == 'category':
            return super().get_queryset().filter(category=pk)
        elif keyword:
            vector = SearchVector('title', weight='A') + SearchVector('description', weight='B') + SearchVector('content', weight='C')
            query = SearchQuery(keyword)
            rank = SearchRank(vector, query)
            return super().get_queryset().annotate(rank=rank).filter(rank__gt=0).order_by('-rank')
        else:
            return super().get_queryset()

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        page_obj = context['page_obj']
        context['page_list'] = get_page_list(page_obj.number, page_obj.paginator.num_pages, self.paginate_by)
        context['tags'] = Tag.objects.all().annotate(article_count=Count('article'))
        context['categories'] = Category.objects.all()
        context['all_article_count'] = Article.objects.count()
        context['popular_articles'] = Article.objects.all().order_by('-viewed')[:5]
        context['keyword'] = self.request.GET.get('keyword', '')
        if self.kwargs.get('filter_type'):
            blog_title = self.kwargs.get('slug').capitalize()
        else:
            blog_title = 'Bloq'

        context['blog_title'] = blog_title
        
        return context


class BlogDetailView(DetailView):
    template_name = 'blog-detail.html'
    context_object_name = 'article'
    model = Article

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        object = self.get_object()
        object.viewed = F('viewed') + 1
        object.save(const_updated_date=True)
        current_pk = object.pk
        context['prev_article'] = self.model.objects.filter(pk__lt=current_pk).order_by('-pk').first()
        context['categories'] = Category.objects.all()
        context['tags'] = Tag.objects.all().annotate(article_count=Count('article'))
        context['all_article_count'] = Article.objects.count()
        context['popular_articles'] = Article.objects.all().order_by('-viewed')[:5]
        context['next_article'] = self.model.objects.filter(pk__gt=current_pk).order_by('pk').first()
        return context

blog/templates/blog-detail.html
{% extends 'layout.html' %}
{% block title %}
<title>Blog - Compar Academy İxtisaslaşmış Tədris Mərkəzi</title>
{% endblock title %} 
{% load static %} {% block meta_tags %} {% endblock meta_tags %} {% block main %}
<section id="blog-detail-first">
  <div class="blog-detail-first-main-box">
    <img class="img-fluid" src="{% static "assets/blog-detail-img1.png" %}"
    alt="" />
    <div class="img-overlay"></div>
    <div class="blog-detail-first-title">
      <h1>Blogun ətraflı detalları</h1>
    </div>
  </div>
</section>
<section id="full-sided">
  <div class="container-fluid">
    <div class="row d-flex align-items-center">
      <div class="col-12 col-lg-6">
        <img src="{{ article.main_image.url }}" alt="" />
      </div>
      <div class="col-12 col-lg-6">
        <div class="full-sided-content">{{ article.content | safe }}</div>
      </div>
    </div>
  </div>
</section>
<section id="blog-images">
  <div class="container-fluid">
    <div class="row row-gap-4">
      {% for image in article.articleimage_set.all %}
      <div class="col-12 col-lg-6">
        <img src="{{ image.image_file.url }}" alt="" />
      </div>
      {% endfor %}
    </div>
  </div>
</section>
{% endblock main %}

blog/templates/blog.html
{% extends 'layout.html' %}
{% block title %}
<title>Blog - Compar Academy İxtisaslaşmış Tədris Mərkəzi</title>
{% endblock title %} 
{% load static %}
{% block meta_tags %}
  <meta name="description" content="Proqramlaşdırma, dizayn və digər texnoloji sahələrlə bağlı maraqlı məqalələr, rəqəmsal dünyadan ən son xəbərlər oxumaq üçün keçid edə bilərsiniz.">
  <meta property="og:title" content="Blog  - Compar Academy İxtisaslaşmış Tədris Mərkəziniz" />
  <meta property="og:description" content="Proqramlaşdırma, dizayn və digər texnoloji sahələrlə bağlı maraqlı məqalələr, rəqəmsal dünyadan ən son xəbərlər oxumaq üçün keçid edə bilərsiniz." />
  <meta property="og:type" content="website" />
  <meta property="og:url" content="{{ request.build_absolute_uri }}" />
  <meta property="og:image" content="{% static "assets/compar-logo-header.png" %}" />
{% endblock meta_tags %}
{% block main %}
<section id="blog-first">
  <div class="blog-first-main-box">
    <img class="img-fluid" src="{% static "assets/faq-first.png" %}" alt="" />
    <div class="img-overlay"></div>
    <div class="blog-first-title">
      <h1>Bloglar</h1>
    </div>
  </div>
</section>
<section id="blogs">
  <div class="container-fluid tags-container">
    <div class="row">
      {% for article in articles %}
      <div class="col-12 col-lg-6">
        <div class="blog-main">
          <img class="bigger-img" src="{{ article.get_image }}" alt="" />
          <div class="blog-name asset-tag">
            {% for tag in article.tags.all %}
              {{ tag.title }}
            {% endfor %}
          </div>
          <div class="underside">
            <h3><a href="{{ article.get_absolute_url }}">{{ article.title }}</a></h3>
            <p>{{ article.description }}</p>
          </div>
          <div class="blog-button">
            <a href="{{ article.get_absolute_url }}"><i class="fa-solid fa-angle-right"></i></a>
          </div>
        </div>
      </div>
      {% endfor %}
    </div>
  </div>
</section>
<section id="section-pagination">
  <div class="d-flex justify-content-center projects-pagination">
    <nav aria-label="Page navigation example">
      <ul class="pagination">
        {% if is_paginated %}
          {% if page_obj.has_previous %}
            <li class="page-item">
              <a class="page-link" href="?page=1" aria-label="First">
                <span aria-hidden="true">&laquo;&laquo;</span>
              </a>
            </li>
            <li class="page-item">
              <a class="page-link" href="?page={{ page_obj.previous_page_number }}" aria-label="Previous">
                <span aria-hidden="true">&laquo;</span>
              </a>
            </li>
          {% endif %}
          {% for i in paginator.page_range %}
            {% if page_obj.number == i %}
              <li class="page-item active"><span class="page-link">{{ i }}</span></li>
            {% else %}
              <li class="page-item"><a class="page-link" href="?page={{ i }}">{{ i }}</a></li>
            {% endif %}
          {% endfor %}
          {% if page_obj.has_next %}
            <li class="page-item">
              <a class="page-link" href="?page={{ page_obj.next_page_number }}" aria-label="Next">
                <span aria-hidden="true">&raquo;</span>
              </a>
            </li>
            <li class="page-item">
              <a class="page-link" href="?page={{ paginator.num_pages }}" aria-label="Last">
                <span aria-hidden="true">&raquo;&raquo;</span>
              </a>
            </li>
          {% endif %}
        {% endif %}
      </ul>
    </nav>
  </div>
</section>
{% endblock main %}