blog/urls.py
from django.urls import path
from blog import views

app_name = 'blog'

urlpatterns = [
    path('', views.BlogListView.as_view(), name='blog-list'),
    path('article/<int:pk>/<str:slug>/', views.BlogDetailView.as_view(), name='blog-detail'),
    path('tag/<int:pk>/<str:slug>/', views.BlogListView.as_view(), kwargs={'filter_type': 'tag'}, name='blog-tag'),
    path('category/<int:pk>/<str:slug>/', views.BlogListView.as_view(), kwargs={'filter_type': 'category'}, name='blog-category'),
    path('search/', views.BlogListView.as_view(), name='blog-search'),
]

compar_new/urls.py
from django.contrib import admin
from django.urls import include, path
from os import getenv
from django.conf.urls.static import static
from django.conf import settings
from django.views.generic import TemplateView
from django.contrib.sitemaps.views import sitemap
from compar_new.sitemaps import ArticleSitemap, CategorySitemap, StaticViewSitemap, TagSitemap
from django.conf.urls.i18n import i18n_patterns
from . import views

sitemaps = {
    'static': StaticViewSitemap,
    'article': ArticleSitemap,
    'tag': TagSitemap,
    'category': CategorySitemap
}

urlpatterns = [
    # path('robots.txt', TemplateView.as_view('')),
    path(getenv('ADMIN_URL'), admin.site.urls),
    path('i18n/', include('django.conf.urls.i18n')),
    path('sitemap.xml', sitemap, {'sitemaps': sitemaps}, name='django.contrib.sitemaps.views.sitemap'),
    path('robots.txt', TemplateView.as_view(template_name='robots.txt', content_type='text/plain'), name='robots'),
    path('ckeditor/', include('ckeditor_uploader.urls')),
    
] + static(settings.MEDIA_URL)




handler404 = 'compar_new.views.handler_error_view'
handler500  = 'compar_new.views.handler_error_view'


urlpatterns += i18n_patterns(
    path('blog/', include('blog.urls')),
    path('events/', include('event.urls')),
    path('', include('promotion.urls')),
    path('courses/', include('course.urls')),
)

event/urls.py
from django.urls import path
from . import views

app_name = 'event'

urlpatterns = [
    path('', views.events_list, name='events'),
    path('<int:pk>/<str:slug>/', views.event_detail, name='event-detail')
]

event/models.py
from django.db import models
from shared.urlutils import get_slug
from django.urls import reverse

CATEGORY_CHOICES = [
    ('xəbər', 'Xəbər'),
    ('tədbir', 'Tədbir'),
]

class Events(models.Model):
    title = models.CharField(max_length=100, null=False, blank=False, verbose_name='Başlıq')
    slug = models.CharField(max_length=100, blank=True)
    description = models.TextField(null=False, blank=False, verbose_name='Mətn')
    image = models.ImageField(upload_to='course/', null=False, blank=False, verbose_name='Şəkil')
    category = models.CharField(max_length=30, choices=CATEGORY_CHOICES,verbose_name='Kateqoriya')
    updated = models.DateField(auto_now=True, verbose_name='Yenilənmə Tarixi')
    created = models.DateField(auto_now_add=True, verbose_name='Yaradılma Tarixi')

    class Meta:
        ordering = ['-created']
        verbose_name = 'Tədbir'
        verbose_name_plural = 'Tədbirlər'

    def __str__(self):
        return self.title + ' tədbir'
    
    def save(self, *args, **kwargs):
        self.slug = get_slug(self.title)
        return super().save(*args, **kwargs)
    
    def get_absolute_url(self):
        return reverse("event-detail", kwargs={"pk": self.pk, 'slug': self.slug})

event/forms.py
from django import forms
from .models import EventApply

class EventApplyForm(forms.ModelForm):
    
    class Meta:
        model = EventApply
        exclude = ('declined', 'event')
        widgets = {
            'name': forms.TextInput(attrs={'class': 'comment-form-input', 'placeholder': 'Ad Soyad'}),
            'email': forms.TextInput(attrs={'class': 'comment-form-input', 'placeholder': 'Email Ünvanı'}),
            'phone': forms.TextInput(attrs={'class': 'comment-form-input', 'placeholder': 'Telefon Nömrəsi'}),
        }
    
    def save(self, event):
        event_apply = EventApply(event=event, **self.cleaned_data)
        event_apply.save()
        return event_apply

event/views.py
from django.shortcuts import render, get_object_or_404
from .models import Events

def events_list(request):
    events = Events.objects.all()
    return render(request, 'events.html', {'events': events})

def event_detail(request, pk, slug):
    event = get_object_or_404(Events, pk=pk, slug=slug)
    return render(request, 'event-detail.html', {'event': event})

event/templates/event-detail.html
{% extends 'layout.html' %}
{% block title %}
<title>Xəbərlər & Tədbirlər - Compar Academy İxtisaslaşmış Tədris Mərkəzi</title>
{% endblock title %} 
{% load static %}
{% block meta_tags %}
  <meta name="description" content="Tədbirlər və xəbərlər bölməsi sizə Compar Academy-nin ən son fəaliyyətləri və aktual xəbərləri barədə məlumat təqdim edir.">
  <meta property="og:title" content="Xəbərlər & Tədbirlər  - Compar Academy İxtisaslaşmış Tədris Mərkəziniz" />
  <meta property="og:description" content="Tədbirlər və xəbərlər bölməsi sizə Compar Academy-nin ən son fəaliyyətləri və aktual xəbərləri barədə məlumat təqdim edir." />
  <meta property="og:type" content="website" />
  <meta property="og:url" content="{{ request.build_absolute_uri }}" />
  <meta property="og:image" content="{% static "assets/compar-logo-header.png" %}" />
{% endblock meta_tags %}
{% block main %}
<section id="events-detail-main">
  <div class="container-fluid">
    <div class="row">
      <div class="col-12 col-lg-6 order2">
        <div class="d-flex">
          <span>{{ event.category|title }}</span>
          <p class="time">{{ event.created }}</p>
        </div>
        <h5>{{ event.title }}</h5>
        <p class="content">{{ event.description }}</p>
      </div>
      <div class="col-12 col-lg-6 order1">
        <img src="{{ event.image.url }}" alt="" />
      </div>
    </div>
  </div>
</section>
{% endblock main %}

event/templates/events.html
{% extends 'layout.html' %}
{% block title %}
<title>Xəbərlər & Tədbirlər - Compar Academy İxtisaslaşmış Tədris Mərkəzi</title>
{% endblock title %} 
{% load static %}
{% block meta_tags %}
  <meta name="description" content="Tədbirlər və xəbərlər bölməsi sizə Compar Academy-nin ən son fəaliyyətləri və aktual xəbərləri barədə məlumat təqdim edir.">
  <meta property="og:title" content="Xəbərlər & Tədbirlər  - Compar Academy İxtisaslaşmış Tədris Mərkəziniz" />
  <meta property="og:description" content="Tədbirlər və xəbərlər bölməsi sizə Compar Academy-nin ən son fəaliyyətləri və aktual xəbərləri barədə məlumat təqdim edir." />
  <meta property="og:type" content="website" />
  <meta property="og:url" content="{{ request.build_absolute_uri }}" />
  <meta property="og:image" content="{% static "assets/compar-logo-header.png" %}" />
{% endblock meta_tags %}

{% block main %}
<section id="events-first">
  <div class="events-first-main-box">
    <img class="img-fluid" src="{% static "assets/events-first.png" %}" alt=""
    />
    <div class="img-overlay"></div>
    <div class="events-first-title">
      <h1>Xəbər & Tədbirlər</h1>
    </div>
  </div>
</section>
<section id="news-events-switch">
  <div class="d-flex justify-content-center switcher">
    <h5 class="active newstoggle">Xəbərlər</h5>
    <h5 class="eventstoggle">Tədbirlər</h5>
  </div>
  <div class="news container-fluid">
    <div class="row">
      {% for event in events %} {% if event.category == 'xəbər' %}
      <div class="col-12 col-md-6 col-lg-4">
        <div class="main-box">
          <img class="img-fluid" src="{{ event.image.url }}" alt="" />
          <span>{{ event.category|title }}</span>
          <h6>{{ event.title }}</h6>
          <p class="box-content">{{ event.description|slice:":120" }}...</p>
          <div class="d-flex">
            <p class="time">{{ event.created }}</p>
            <a href="{% url 'event:event-detail' pk=event.pk slug=event.slug %}"
              >ətraflı</a
            >
            <i class="fa-solid fa-chevron-right"></i>
          </div>
        </div>
      </div>
      {% endif %} {% endfor %}
    </div>
  </div>
  <div class="events container-fluid">
    <div class="row">
      {% for event in events %} {% if event.category == 'tədbir' %}
      <div class="col-12 col-md-6 col-lg-4">
        <div class="main-box">
          <img class="img-fluid" src="{{ event.image.url }}" alt="" />
          <span>{{ event.category|title  }}</span>
          <h6>{{ event.title }}</h6>
          <p class="box-content">{{ event.description|slice:":120" }}</p>
          <div class="d-flex">
            <p class="time">{{ event.created }}</p>
            <a href="{% url 'event:event-detail' pk=event.pk slug=event.slug %}"
              >ətraflı</a
            >
            <i class="fa-solid fa-chevron-right"></i>
          </div>
        </div>
      </div>
      {% endif %} {% endfor %}
    </div>
  </div>
</section>
{% endblock main %}