blog/urls.py
from django.urls import path
from blog import views

app_name = 'blog'

urlpatterns = [
    path('', views.BlogListView.as_view(), name='blog-list'),
    path('article/<int:pk>/<str:slug>/', views.BlogDetailView.as_view(), name='blog-detail'),
    path('tag/<int:pk>/<str:slug>/', views.BlogListView.as_view(), kwargs={'filter_type': 'tag'}, name='blog-tag'),
    path('category/<int:pk>/<str:slug>/', views.BlogListView.as_view(), kwargs={'filter_type': 'category'}, name='blog-category'),
    path('search/', views.BlogListView.as_view(), name='blog-search'),
]

compar_new/urls.py
from django.contrib import admin
from django.urls import include, path
from os import getenv
from django.conf.urls.static import static
from django.conf import settings
from django.views.generic import TemplateView
from django.contrib.sitemaps.views import sitemap
from compar_new.sitemaps import ArticleSitemap, CategorySitemap, StaticViewSitemap, TagSitemap
from django.conf.urls.i18n import i18n_patterns
from . import views

sitemaps = {
    'static': StaticViewSitemap,
    'article': ArticleSitemap,
    'tag': TagSitemap,
    'category': CategorySitemap
}

urlpatterns = [
    # path('robots.txt', TemplateView.as_view('')),
    path(getenv('ADMIN_URL'), admin.site.urls),
    path('i18n/', include('django.conf.urls.i18n')),
    path('sitemap.xml', sitemap, {'sitemaps': sitemaps}, name='django.contrib.sitemaps.views.sitemap'),
    path('robots.txt', TemplateView.as_view(template_name='robots.txt', content_type='text/plain'), name='robots'),
    path('ckeditor/', include('ckeditor_uploader.urls')),
    
] + static(settings.MEDIA_URL)




handler404 = 'compar_new.views.handler_error_view'
handler500  = 'compar_new.views.handler_error_view'


urlpatterns += i18n_patterns(
    path('blog/', include('blog.urls')),
    path('events/', include('event.urls')),
    path('', include('promotion.urls')),
    path('courses/', include('course.urls')),
)

course/urls.py
from django.urls import path
from . import views

app_name = 'course'

urlpatterns = [
    path('', views.courses, name='courses'),
    path('<int:pk>/<str:slug>/', views.course_detail, name='course-detail'),
]

event/urls.py
from django.urls import path
from . import views

app_name = 'event'

urlpatterns = [
    path('', views.events_list, name='events'),
    path('<int:pk>/<str:slug>/', views.event_detail, name='event-detail')
]

promotion/urls.py
from django.urls import path
from promotion import views

app_name = 'promotion'
urlpatterns = [
    path('', views.home, name='home'),
    path('contact/', views.contact, name='contact'),
    path('about/', views.about, name='about'),
    path('faq/', views.faq, name='faq'),
    path('graduates/', views.graduates, name='graduates'),
    path('method/', views.method, name='method'),
    path('packages/', views.packages, name='packages'),
    path('corporative/', views.corporative, name='corporative'),
    path('appointment/', views.appointment, name='appointment'),
    path('privacy/', views.privacy, name='privacy'),
]

templates/error.html
{% extends 'layout.html' %}
{% block title %}
  <title>Səhifə tapılmadı</title>
{% endblock title %}
{% load static %}
{% block main %}
<body>
  <div class="error-container">
    <h1>404</h1>
    <h2>Səhifə tapılmadı</h2>
    <p>Üzr istəyirik, axtardığınız səhifə mövcud deyil.</p>
    <a href="{% url 'promotion:home' %}" class="btn">Ana səhifəyə keçin</a>
  </div>
</body>
</html>
{% endblock main %}

templates/layout.html
{% load static %}
{% load i18n %}
{% load course_tags %} {% get_courses as courses %}
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <meta name="keywords" content="Proqramlaşdırma, proqramlaşdırma dərsləri, proqramlaşdırma kursları, dizayn kursları, qrafik dizayn kursu, veb dizayn kursu, ui ux kursu, interyer dizayn, interyer dizayn kursu, ofis proqramları, Frontend dərsləri, Backend dərsləri, Full-stack dərsləri, kodlaşdırma dərsləri">
    <meta name="robots" content="index, follow">
    {% block meta_tags %}{% endblock meta_tags %}
    {% block title %}{% endblock title %}
    <title>Compar Academy</title>
    <link rel="icon" href="{% static "assets/head-favicon.png" %}" type="image/x-icon">
    <link rel="preconnect" href="https://fonts.googleapis.com" />
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin />
    <link
      href="https://fonts.googleapis.com/css2?family=Poppins:ital,wght@0,100;0,200;0,300;0,400;0,500;0,600;0,700;0,800;0,900;1,100;1,200;1,300;1,400;1,500;1,600;1,700;1,800;1,900&display=swap"
      rel="stylesheet"
    />
    <link
      rel="stylesheet"
      href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.5.1/css/all.min.css"
      integrity="sha512-DTOQO9RWCH3ppGqcWaEA1BIZOC6xxalwEsw9c2QQeAIftl+Vegovlnee1c9QX4TctnWMn13TZye+giMm8e2LwA=="
      crossorigin="anonymous"
      referrerpolicy="no-referrer"
    />
    <link
      rel="stylesheet"
      href="https://cdn.jsdelivr.net/npm/swiper@11/swiper-bundle.min.css"
    />
    <link rel="stylesheet" href="{% static "vendors/bootstrap.min.css" %}" />
    <link rel="stylesheet" href="{% static "styles/style.css" %}" />
  </head>
  <body>
    <header>
      <div class="topside">
        <div class="container-fluid">
          <div class="row align-items-center">
            <div class="col-6">
              <div class="streetname">Shamil Azizbeyov street</div>
            </div>
            <div class="col-6">
              <div class="topside-icons">
                <a href="https://www.instagram.com/compar_academy/">
                  <i class="fa-brands fa-instagram"></i>
                </a>
                <a href="https://www.facebook.com/comparacademy/">
                  <i class="fa-brands fa-facebook-f"></i>
                </a>
                <a href="https://az.linkedin.com/company/compar-academy">
                  <i class="fa-brands fa-linkedin-in"></i>
                </a>
              </div>
            </div>
          </div>
        </div>
      </div>
      <div class="navbar">
        <div class="container-fluid">
          <div class="logo">
            <a href="{% url 'promotion:home' %}">
              <img src="{% static "assets/compar-logo-header.png" %}" alt="" />
            </a>
          </div>
          <div class="responsive-nav-menu">
            <a href="tel:+994552042729"><i style="padding-right: 20px" class="fa-solid fa-phone-volume"></i></a>
            <i class="fa-solid fa-bars"></i>
          </div>
          <div class="nav-menu">
            <ul class="list-unstyled d-flex">
              <li><a href="{% url 'promotion:about' %}">Haqqımızda</a></li>
              <li class="courses">
                <a href="{% url 'course:courses' %}">Kurslar</a>
              </li>
              <li><a href="{% url 'event:events' %}">Tədbirlər</a></li>
              <li><a href="{% url 'promotion:faq' %}">FAQ</a></li>
              <li><a href="{% url 'promotion:contact' %}">Əlaqə</a></li>
            </ul>
          </div>
        </div>
      </div>
      <div class="responsive-openmenu">
        <ul class="list-unstyled outside-ul">
          <li>
            <div class="isopenmenu">
              <a href="{% url 'promotion:about' %}">Haqqımızda</a>
              <i class="fa-solid fa-chevron-down"></i>
            </div>
            <div class="openmenu-divider-outside"></div>
            <ul class="list-unstyled inside-ul">
              <li><a href="{% url 'promotion:method' %}">Tədris metodikası</a></li>
              <div class="openmenu-divider-inside"></div>
              <li><a href="{% url 'promotion:graduates' %}">Məzunlarımız</a></li>
              <div class="openmenu-divider-inside"></div>
            </ul>
          </li>
          <li>
            <div class="isopenmenu">
              <a href="{% url 'course:courses' %}">Kurslar</a>
            </div>
            <div class="openmenu-divider-outside"></div>
          </li>
          <li>
            <div class="isopenmenu">
              <a href="{% url 'event:events' %}">Tədbirlər</a>
            </div>
            <div class="openmenu-divider-outside"></div>
          </li>
          <li><a href="{% url 'blog:blog-list' %}">Blog</a></li>
          <div class="openmenu-divider-outside"></div>
          <li><a href="{% url 'promotion:faq' %}">FAQ</a></li>
          <div class="openmenu-divider-outside"></div>
          <li>
            <div class="isopenmenu">
              <a href="{% url 'promotion:contact' %}">Əlaqə</a>
            </div>
            <div class="openmenu-divider-outside"></div>
          </li>
        </ul>
        <div class="responsive-openmenu-icons">
          <a href="https://www.instagram.com/compar_academy/">
            <i class="fa-brands fa-instagram"></i>
          </a>
          <a href="https://www.facebook.com/comparacademy/">
            <i class="fa-brands fa-facebook-f"></i>
          </a>
          <a href="https://az.linkedin.com/company/compar-academy">
            <i class="fa-brands fa-linkedin-in"></i>
          </a>
        </div>
      </div>
    </header>
    {% block main %}{% endblock main %}
    <footer>
      <div class="footer">
        <div class="container-fluid main">
          <div class="row row-gap-4">
            <div class="col-sm-12 col-lg-2 order4">
              <div class="logo">
                <a href="{% url 'promotion:home' %}">
                  <img src="{% static "assets/compar-logo-footer.png" %}" alt="" />
                </a>
              </div>
            </div>
            <div class="col-sm-12 col-lg-6 order3">
              <div class="footer-content">
                <div>
                  It is a long established fact that a reader will be<br />distracted
                  by the readable content of a page when<br />looking at its
                  layout
                </div>
                <div class="contentsecond">
                  4517 Washington Ave. Manchester, Kentucky 39495
                </div>
                <span>(239) 555-0108</span><span>(303) 555-0105</span>
              </div>
            </div>
            <div class="col-sm-12 col-lg-2 order1">
              <div class="ultitle">Compar Academy</div>
              <ul class="list-unstyled">
                <li><a href="{% url 'promotion:about' %}">Haqqımızda</a></li>
                <li><a href="{% url 'event:events' %}">Tədbirlər</a></li>
                <li><a href="{% url 'promotion:faq' %}">FAQ</a></li>
                <li><a href="{% url 'promotion:graduates' %}">Məzunlar</a></li>
                <li><a href="{% url 'promotion:contact' %}">Əlaqə</a></li>
              </ul>
            </div>
            <div class="col-sm-12 col-lg-2 order2">
              <div class="ultitle">Kurslarımız</div>
              <ul class="list-unstyled">
                {% for course in courses|slice:":5" %}
                  <li><a href="{% url 'course:course-detail' pk=course.pk slug=course.slug %}">{{ course.title }}</a></li>
                {% endfor %}
              </ul>
            </div>
          </div>
        </div>
        <div class="divider"></div>
        <div class="copyright">
          <div class="container-fluid">
            <div class="row align-items-center">
              <div class="col-6">
                <div id="copyright" class="copyrightcontent"></div>
              </div>
              <div class="col-6">
                <div class="footer-icons">
                  <a href="https://www.instagram.com/compar_academy/">
                    <i class="fa-brands fa-instagram"></i>
                  </a>
                  <a href="https://www.facebook.com/comparacademy/">
                    <i class="fa-brands fa-facebook-f"></i>
                  </a>
                  <a href="https://az.linkedin.com/company/compar-academy">
                    <i class="fa-brands fa-linkedin-in"></i>
                  </a>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
    </footer>
    {% block scripts %}{% endblock scripts %}
    <script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/swiper@11/swiper-bundle.min.js"></script>
    <script src="{% static "js/main.js" %}"></script>
    <script src="{% static "js/about.js" %}"></script>
    <script src="{% static "js/events.js" %}"></script>
    <script src="{% static "js/faq.js" %}"></script>
    <script>
      var date = new Date();
      var year = date.getFullYear();
      var copyrightcontent = "© " + year + " Compar Academy. Bütün hüquqlar qorunur";
      document.getElementById("copyright").innerHTML = copyrightcontent;
    </script>
  </body>
</html>